version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - 'mongo'
  frontend:
    build: ./frontend/
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
  mongo-seed: 
    image: fvilers/mongo-seed:1.0.0
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./data:/data
    command:
      "mongoimport --host mongo --port 27017 --db data --mode upsert --type json --file /data/users.json --jsonArray"
  mongo: 
    image: 'mongo:4.2.2'
    ports:
      - '27017:27017'